### ISSUE TITLE
Crash with painterResource

### ISSUE THREAD

**Issue by Miggets7** [Chaintech-Network/compose_multiplatform_date_time_picker#6]
When adding this lib as a dependency and using `painterResource`, the app crashes on Android:
```
java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
at org.jetbrains.compose.resources.AndroidContextProviderKt.getAndroidInstrumentedContext(AndroidContextProvider.kt:16)
at org.jetbrains.compose.resources.ResourceReader_androidKt$getPlatformResourceReader$1.getInstrumentedAssets(ResourceReader.android.kt:22)
at org.jetbrains.compose.resources.ResourceReader_androidKt$getPlatformResourceReader$1.getResourceAsStream(ResourceReader.android.kt:79)
at org.jetbrains.compose.resources.ResourceReader_androidKt$getPlatformResourceReader$1.read(ResourceReader.android.kt:29)
at org.jetbrains.compose.resources.ImageResourcesKt$loadImage$2.invokeSuspend(ImageResources.kt:158)
at org.jetbrains.compose.resources.ImageResourcesKt$loadImage$2.invoke(Unknown Source:8)
at org.jetbrains.compose.resources.ImageResourcesKt$loadImage$2.invoke(Unknown Source:2)
at org.jetbrains.compose.resources.AsyncCache$getOrLoad$2$deferred$1$1.invokeSuspend(AsyncCache.kt:19)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
at org.jetbrains.compose.resources.ResourceState_blockingKt.rememberResourceState(ResourceState.blocking.kt:46)
at org.jetbrains.compose.resources.ImageResourcesKt.imageResource(ImageResources.kt:60)
at org.jetbrains.compose.resources.ImageResourcesKt.painterResource(ImageResources.kt:44)
```

**Comment by Parthib-Iepssols** [comment]
Hey there, if the issue is resolved please update the solution. Thank You.

**Comment by Miggets7** [comment]
@Parthib-Iepssols I don't understand what you mean. The issue is still there. When you add it to a new KKM Compose project, it crashes when using `painterResource`

**Comment by erickvelasco11** [comment]
I have fall in this issue too.
When I update the library to version 1.0.5 and I try to show an image like

`Image(painterResource(Res.drawable.compose_multiplatform), null)`
                    
I got the same error 

`java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.`


My solution... downgrade again to 1.0.3 version

**Comment by santyas** [comment]
> I have fall in this issue too. When I update the library to version 1.0.5 and I try to show an image like
> 
> `Image(painterResource(Res.drawable.compose_multiplatform), null)`
> 
> I got the same error
> 
> `java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.`
> 
> My solution... downgrade again to 1.0.3 version

I had to downgrade it to 1.0.3 as well

**Comment by erickvelasco11** [comment]
Also I have the same error in another project, but I downgrade the library but the issue was not fixed. So, What I did was

- Download a new project (kmp.jetbrains.org)
- Copy the libraries (libs.toml and build.gradle.kts files) to a new project
- Gradle build
- Start

This way I replicate the issue in a new template. After that I remove one by one of the libraries from the build.gradle.kts file and compile until the new template ran again.
I found a library called [Kottie](https://github.com/ismai117/kottie) that is "incompatible" with the libraries of [Chaintech-Network](https://github.com/Chaintech-Network) (Because I'm using three "QrKit", "DateTimePicker" and "CMP pick and crop")

I replaced [Kottie](https://github.com/ismai117/kottie) with [Compottie](https://github.com/alexzhirkevich/compottie) and all worked again. I know that all this was a big pain, and there are something in Chaintech-Network libraries that is not working fine, but at least my project is running now.
Maybe you have some library "Incompatible" with these other libraries.

**Comment by mobiletoly** [comment]
I don't have Kottie in my project (actually I use Compottie), but it still crashes with the same error

**Comment by mobiletoly** [comment]
just FYI, 1.0.5 works for me now, looks like the problem was because I still used the old compose plugin (pre 1.7). so make sure to update your versions:

[versions]
compose-plugin = "1.7.0-rc01"

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }

**Comment by mobiletoly** [comment]
Yeah, I've added 1.7.0 instead of 1.7.0-rc01 and it works just fine with datetimepicker 1.0.5. I'm able to use all that new compose 1.7 stuff (including alpha03 PreCompose). here is my libs.version.toml just in case if you want to take a look at my dependencies

```
[versions]
kotlin = "2.0.20"
kotlinx-datetime = "0.6.1"
compose = "1.7.3"
compose-plugin = "1.7.0"
agp = "8.7.1"
android-minSdk = "27"
android-compileSdk = "34"
android-targetSdk = "34"
androidx-activityCompose = "1.9.2"
androidx-media3-exoplayer = "1.4.1"
androidx-datastore-preferences = "1.1.1"
androidx-lifecycle="2.8.2"
junit = "4.13.2"
ktor = "2.3.12"
kamel = "0.9.5"
koin-core = "4.0.0"
koin-compose = "4.0.0"
multiplatformSettings = "1.1.1"
kermit = "2.0.3"
sqldelight = "2.0.2"
composeIcons = "1.1.1"
precompose = "1.7.0-alpha03"
markdownRenderer = "0.26.0"
compottie = "1.1.2"
moko-mvvmFlow = "0.16.1"
purchases-kmp = "1.1.2+13.5.0"
molecule-runtime = "2.0.0"
datetimepicker = "1.0.5"

[libraries]
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-android = { module = "androidx.compose.ui:ui-android", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore-preferences" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-logger = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
kamel-image = { module = "media.kamel:kamel-image", version.ref = "kamel" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose" }
multiplatformSettings-core = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }
multiplatformSettings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "multiplatformSettings" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
composeIcons-fontAwesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeIcons" }
precompose-core = { module = "moe.tlaster:precompose", version.ref = "precompose" }
precompose-molecule = { module = "moe.tlaster:precompose-molecule", version.ref = "precompose" }
markdownRenderer = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdownRenderer" }
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
moko-mvvmFlow = { module = "dev.icerock.moko:mvvm-flow", version.ref = "moko-mvvmFlow" }
moluecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule-runtime" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidx-media3-exoplayer" }
sqldelight-androidDriver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-nativeDriver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-primitiveAdapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
purchases-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "purchases-kmp" }
purchases-result = { module = "com.revenuecat.purchases:purchases-kmp-result", version.ref = "purchases-kmp" }
datetimepicker = { module = "network.chaintech:kmp-date-time-picker", version.ref = "datetimepicker" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
```

**Comment by santyas** [comment]
Thank you! I have some config quite different, for example AGP I have 8.2.2. MinSDK 24 (I will try with 26).

**Comment by ctn-mobile-innovation** [comment]
Please Upgrade your compose-multiplatform version.
